### PR TITLE
Milestone Friendships version 1

### PR DESCRIPTION
**Pull request by KabohaJeanMark**
-  Update the README with a nice visual walkthrough on how the project works with screenshots at each stage
-  Add a model for friendships with the relevant associations.
-  Enable a logged-in user to view all users with a button to Add Friend
-  Add a check that prevents a user from sending a friend request to the same user more than once.
-  Add a page My Pending Friendships do display all pending friend requests with options to Accept or Decline.
-  Work on the Update and Delete actions in the friendships controller to enable a user to accept a friendship request or decline it.
-  Add Unit tests with RSpec for the models and their validations.
-  Add integration tests for a project walkthrough sampling the create post method for a signed-in user.

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: INVALID** :red_circle: 

Hello @KabohaJeanMark ,

All efforts to run your application proved unsuccessful. Attempts to create or migrate the database kept producing this error: `ArgumentError: wrong number of arguments (given 3, expected 2)
` 
The likely cause could be that you generated one your migrations wrongly.

As a result of the above, I was unable to review the project.

Kindly submit a working version of the project.

Cheers :smile: With respect :tophat:

**Comment by KabohaJeanMark** [comment]
Thanks 👍🏾, @george-shammar for the clear feedback about the bug in the review.
Sorry about the DB error.

The fault was mine and I fixed 🧑‍🔧  the way I had done my PostgreSQL installation so that by default the database.yml file picks the default Postgres username and password of the user running the code.
The project can now be run and checked on another machine.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad**. 

### Well-done 💯 
    1. The app runs just fine
    2. The PR description is clearly stated.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] A logged-in user is able to send themselves a friend request. This should not be the expected app's behaviour. Give this a quick fix.
- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from Pathwright)
- [x] Once a friend request has been accepted, the add friend button in both the users' and single user page still exists. Users can then send each other requests back and forth endlessly. Look into this behaviour. 
- [x] The testing command in the readme file should be `rspec` and not `rpsec`.
- [x] Add unit tests for all the models of your app.


#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by KabohaJeanMark** [comment]
Thanks 👍🏾  for the clear and concise feedback @mke2111.
I have worked on all of the required changes 💪🏾

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Changes Required :yellow_circle:            
### Hello @KabohaJeanMark :wave: 

Thanks for working on the requirements suggested by the previous reviewer. Your project meets almost all the requirements, the following are some of the highlights:
- the relationship between entities is correctly represented and 
- descriptive and well-written pull request description.

Please work on the following missing requirement and submit for a new review:
- Once a friendship request is accepted, single-user page still displays a button to add the same friend, kindly make sure to remove the button after friendship is accepted.
- Please include more tests and test public methods available in your models. for example all public methods inside user model have not been tested.

#### If you have any questions feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Comment by KabohaJeanMark** [comment]
Thanks, 👍🏾  @bini-i for the feedback.
I have done all the requested changes ♻️  fixing the bug on the single user show page and adding many more tests for associations, validations and public instance methods to make the project better.

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

@KabohaJeanMark , Thanks for making the required changes from the last review.
:heavy_check_mark: You have tested your public method in user.rb and added more tests.
:heavy_check_mark: You have implemented the required change as well.
:heavy_check_mark: Your repo looks professional.

Extra :clap: :clap: : I like the communication skill you've displayed through out the review process by providing update after each review. :+1: 

You may go ahead and merge this branch and proceed to the next milestone.

I wish you good luck.

**Cheers** :smile: **With respect** :tophat:

**Pull request merged**
