### PR TITLE
Milestone 1: Prepare data architecture documentation

### PR DESCRIPTION
**Pull request by KabohaJeanMark**
- Update the linters, ruby version to the current specifications.
- Create an Entity-relationship Diagram to model the associations and interactions of the database entities for the Social Media Project.
- Save it in a created docs directory.
- Update the README.md with a screenshot of the ERD and information about the project.

### CODE REVIEW

**Review by BrianSammit — COMMENTED** [review]
STATUS: INVALID 🟡 
------------
Hello @KabohaJeanMark, 
Friendly reminder: You should make sure that your repo looks professional before review. 
Please make sure your linters are working properly on GitHub.
Follow the steps below on the forked repo:
* Enable the GitHub Actions in the Actions tab.
* Create the feature/branch and push.
* Start working on the milestone as usual.
* Open a PR from the feature/branch when the work is done.

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

**Comment by KabohaJeanMark** [comment]
Sorry about that. You are quite right @BrianSammit. Thank you 👏🏾  so much for the guidance offered in this quick and friendly Code Review

I should have checked to see that the linters are indeed working. I am going to make sure of this by doing the fixes before I make another Code Review Request.

I have enabled the GitHub actions and now the linters are working properly on GitHub 💪🏾 .

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED 🔴 🛑 
-----------
Hello @KabohaJeanMark, Great job working on this first milestone and fixing the linters checks 👏 👍 
TO HIGHLIGHT: 

- Your repo is professional 
- Your project is professional 
- Your Erd diagram is well placed 

However, there are minor changes to make to complete this milestone 🛠️ see them below 👀 👇 
------------

- [x] Please add the image_link column on the user's table. 

imglink

- [x] You are missing one important table. The like table. Please add it. 

Capture

-------------
Make these minor changes and send ti again for another review 💪 
Reach me on SLACK. 
@ Brian Sammit Cruz Rodriguez

HAPPY CODING!! 😄 
cat

**Comment by KabohaJeanMark** [comment]
Thanks 👍🏾  for the clear feedback @BrianSammit.
The following requested changes have been implemented;
- Add an image_link to the User table
- Add a like table and model associations between it and the User and Post table

**Review by GzimAsani — APPROVED** [review]
# STATUS: Millstone Accepted :green_circle: 

## Hello @KabohaJeanMark, thank you for making all the requested changes. Merge this millstone and I wish you the best of luck with your next ones :+1: 

# HAPPY CODING :computer: :desktop_computer:

**Pull request merged**
